// @generated by protoc-gen-connect-es v0.13.2 with parameter "target=ts"
// @generated from file collo/v1/collo.proto (package collo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ColloStreamRequest, ColloStreamResponse } from "./collo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service collo.v1.ColloService
 */
export const ColloService = {
  typeName: "collo.v1.ColloService",
  methods: {
    /**
     * @generated from rpc collo.v1.ColloService.ColloStream
     */
    colloStream: {
      name: "ColloStream",
      I: ColloStreamRequest,
      O: ColloStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

